### ISSUE TITLE
[BUG] ADD HACKTOBERFEST AND GSSOC BANNER ON THE README FILE

### ISSUE THREAD

**Issue by alo7lika** [ombhojane/explainableai#104]
## Description
To foster community engagement and encourage contributions, we proudly display the Hacktoberfest and GirlScript Summer of Code (GSSoC) banners in our README. Hacktoberfest is an annual event that celebrates open-source contributions, inviting developers of all levels to participate and make their mark in the open-source community. By promoting this event, we aim to inspire contributors to enhance their skills while supporting our project. Similarly, featuring the GSSoC banner highlights our commitment to nurturing young talent and providing a platform for aspiring developers to learn and grow. Together, these banners represent our dedication to inclusivity and collaboration in the tech community, encouraging developers to join us in making a difference through code.

## Steps to Reproduce
Clone the Repository: Begin by cloning the repository that contains the project. This can be done using the Git command line interface, which allows users to create a local copy of the project on their machines.

Install Dependencies: Once the repository is cloned, the next step is to navigate into the project directory and install the necessary dependencies. This is often done using a package manager like npm, which retrieves and installs the libraries and tools required for the application to run.

Start the Application: After all dependencies are installed, users should start the application to verify its functionality. This usually involves executing a command that launches the app on a local server.

Navigate to the Buggy Feature: Users should then access the specific feature or page of the application where the bug is believed to exist. This helps in isolating the problem area.

Perform the Trigger Action: To recreate the bug, users need to perform the action that causes the issue. This might involve clicking buttons, entering data, or navigating through different pages.

Document Behavior: It’s essential to note what the expected behavior of the application is versus what actually happens when the action is performed. This documentation can provide insights into what went wrong.

Capture Error Messages: If any error messages or logs are generated during the process, these should be recorded. Error messages are often vital clues for developers in diagnosing issues.

## Expected Behavior
The expected behavior is for the Hacktoberfest and GSSoC banners to be prominently displayed at the top of the README file, showing support for these open-source events and encouraging contributions.

## Actual Behavior
The current README file does not include the Hacktoberfest and GSSoC banners. Adding these banners would help in promoting the events and attracting more developers to participate and contribute to the project.

## Screenshots (if applicable)
N/A

**Comment by alo7lika** [comment]
ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 
ASSIGN ME THE TASK
TANK YOU @ombhojane !

**Comment by alo7lika** [comment]
> ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 ASSIGN ME THE TASK TANK YOU @ombhojane !

@ombhojane

**Comment by ombhojane** [comment]
Okayy sure @alo7lika go ahead

**Comment by alo7lika** [comment]
> Okayy sure @alo7lika go ahead

ASSIGN ME THE TASK AND ADD LABELS GSSOC EXT 24 AND HACKTOBERFEST
