### ISSUE TITLE
[FEATURE] add scroll top option

### ISSUE THREAD

**Issue by KartikSaxena19** [ombhojane/explainableai#106]
I want to add the button in which when the page is not on the top it will automatically scroll the page up
Kindly assign this issue to me under the tag of gssoc ext and hacktoberfest

**Comment by KartikSaxena19** [comment]
Sorry for this

**Comment by ombhojane** [comment]
nvm, you can look around explainableai package, explore, give it a shot! and raise meaningful PRs! @KartikSaxena19
