### ISSUE TITLE
[FEATURE] Add home button in navbar

### ISSUE THREAD

**Issue by Aditijainnn** [ombhojane/explainableai#107]
## Description

Adding home button beacuse when we go to help/login/register there is no option of going back to home

assign this to me under gssoc ext and hacktoberfest

![image](https://github.com/user-attachments/assets/7f64d5ab-a93c-4721-9bf4-bdb7ace8d2a5)

**Comment by ombhojane** [comment]
This is a python package and not a website

The website you're viewing that's of PIP package manager
