### ISSUE TITLE
Github actions for more connectivity!

### ISSUE THREAD

**Issue by smog-root** [ombhojane/explainableai#118]
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @ombhojane 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

**Comment by nigam-divyanshi-dev** [comment]
please assign this issue to me under gssoc or hacktoberfest so that i can contribute . thankyou .

**Comment by smog-root** [comment]
@nigam-divyanshi-dev i kindly don't need any assistance to complete my issue!!

You can try this on any other issues!!

**Comment by ombhojane** [comment]
Hey you can build 'Auto comment on PR mergs'
other suggested actions have been already created
