### ISSUE TITLE
📝[DOCS] adding Stargazers and Forkers section to readme.md

### ISSUE THREAD

**Issue by amiya-cyber** [ombhojane/explainableai#123]
Issue Description
adding Stargazers and Forkers section to readme.md

Stargazers

Use Case:

1. Bookmarking Projects
2. Discovering Popularity

Benefits:

1. Visibility
2. Feedback Indicator
3. Community Engagement

Forkers

Use Case:

1. Creating Personal Copies
2. Contributing Back

Benefits:

1. Encouraging Innovation
2. Easy Collaboration
3. Building Ownership

ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 AND LEVEL 2 OR LEVEL 3
ASSIGN ME THE WORK
THANK YOU @ombhojane  !
![2024-10-23 (7)](https://github.com/user-attachments/assets/db38983e-1b84-4f2a-a4de-1b66c18d0b55)

**Comment by ombhojane** [comment]
can be more catchy abbreivations possible?

go ahead @amiya-cyber
