### ISSUE TITLE
Enhance and Structure the Contributor Section

### ISSUE THREAD

**Issue by alo7lika** [ombhojane/explainableai#125]
## Description
The current "Contributors" section lacks structure and visual clarity, making it challenging for new users to recognize the valuable contributions of individuals who have worked on the project. This section needs to be enhanced to better showcase contributors, making it more appealing and easier to navigate.

## Steps to Reproduce
1. Go to the main repository page.
2. Scroll down to the "Contributors" section.
3. Observe the layout and information presentation for the contributors.
4. Notice the lack of a clear structure or visual appeal.

## Expected Behavior
The "Contributors" section should be visually engaging, structured, and informative. It should:
- Highlight contributors' profile pictures in a visually appealing grid format.
- Include links to contributors' GitHub profiles for easy access.
- Provide a clear indication of the number of contributions made by each contributor.
- Use consistent design elements to maintain a professional look.

## Actual Behavior
The current section appears plain and lacks clear visual indicators of contributors' profiles and contributions.

## Screenshots (if applicable)
N/A

**Comment by alo7lika** [comment]
@ombhojane assign me the task under GSSOC EXT 24 and HACKTOBERFEST.

**Comment by pameladeysarkar2003** [comment]
@ombhojane please assign the task to me i can contribute to it.

**Comment by alo7lika** [comment]
> @ombhojane assign me the task under GSSOC EXT 24 and HACKTOBERFEST.

@ombhojane
