### ISSUE TITLE
Add Model Comparison Dashboard for Evaluating Multiple ML Models

### ISSUE THREAD

**Issue by imDarshanGK** [ombhojane/explainableai#137]
We need to implement an interactive Model Comparison Dashboard to allow users to evaluate multiple machine learning models side by side. This feature will include:

1} Model Selection
2} Performance Metrics
3} Feature Importance
4} Interactive Visualizations

Thank you,
@ombhojane

**Comment by ombhojane** [comment]
@imDarshanGK go ahead!
