### ISSUE TITLE
Basic Time Series Visualization

### ISSUE THREAD

**Issue by ombhojane** [ombhojane/explainableai#16]
Add simple time series plotting capabilities to help users visualize temporal data.

Approach

- Create basic time series plotting functions
- Add option to include time series plots in report
- Implement simple temporal feature importance

Testing

- Test with sample time series data
- Verify plot generation
- Check integration with existing report generation

**Comment by sharayuanuse** [comment]
I want to work on this issue. Can you assign it to me?

**Comment by ombhojane** [comment]
hey @sharayuanuse go ahead!

**Comment by saniyaahemad12** [comment]
I want to contribute on this
