### ISSUE TITLE
Create Comprehensive User Guide

### ISSUE THREAD

**Issue by ombhojane** [ombhojane/explainableai#3]
Develop detailed documentation to help users understand and effectively use the explainableAI package.

Tasks:
- Write a quick start guide for new users
- Document all public classes and methods with clear descriptions and examples
- Create in-depth tutorials for each major feature

**Comment by Amikumarsingh** [comment]
Hii mentor @sanjay-kv  i would like to contribute for this issue.

**Comment by ombhojane** [comment]
@Amikumarsingh go ahead!

**Comment by alo7lika** [comment]
I would love to contribute, please assign me this work @ombhojane

**Comment by ombhojane** [comment]
This issue has been resolved!
