### ISSUE TITLE
add model_training.py

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [ombhojane/explainableai#30]
A dedicated script for training different models, allowing easy experimentation with hyperparameters and configurations.

**Comment by AKSHITHA-CHILUKA** [comment]
add gssoc and hacktoberfest lables

**Comment by ombhojane** [comment]
@AKSHITHA-CHILUKA go ahead!

**Comment by Bhavya445** [comment]
can u plss assign this to me

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
