### ISSUE TITLE
add user_guide.md

### ISSUE THREAD

**Issue by AKSHITHA-CHILUKA** [ombhojane/explainableai#31]
A markdown file that explains how to use the package, including examples and best practices for generating explanations.

add gssoc and hacktoberfest lables

**Comment by alo7lika** [comment]
Assign me this work, I would like to contribute to it. add labels gssoc and hacktoberfest

**Comment by AKSHITHA-CHILUKA** [comment]
@ombhojane 
add a user_guide.md to explainableai repository. This guide will help users understand the usage of the different modules in your project, including installation steps, module usage, and example workflows.

# ExplainableAI User Guide

## Table of Contents
- [Introduction](#introduction)
- [Installation](#installation)
- [Modules Overview](#modules-overview)
- [How to Use](#how-to-use)
- [Example Workflow](#example-workflow)
- [FAQs](#faqs)

**Comment by xXemran05khanXx** [comment]
assign me

**Comment by Bhavya445** [comment]
can u plss assign this to me
