### ISSUE TITLE
Add a dark mode toggle button

### ISSUE THREAD

**Issue by pavitraag** [ombhojane/explainableai#45]
I would like to add a dark mode toggle button. Please assign me under gssoc-ext and hacktoberfest.

**Comment by ombhojane** [comment]
can you elaborate your usecase? as it's cli based and no user interface we're providing. what you want to say?

**Comment by ombhojane** [comment]
@pavitraag

**Comment by pavitraag** [comment]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/9463e04c-2e3d-4f96-83a1-239121c14465">
Currently this background is in bright color , I want to add a feature to add a black background so that its user choice to switch the background they want and helps in reducing the stress of eye.

**Comment by ombhojane** [comment]
ahh that's pypi package website! 
where every python package has been listed
we have explaianbleai python package only
