### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by archanasingh11** [ombhojane/explainableai#50]
**Description:**

The explainableai website currently lacks a **"Scroll to Top"** button, which is a key feature for enhancing user experience, especially on pages with extensive content. Without this button, users have to manually scroll back to the top of the page, which can be inconvenient and time-consuming.

Implementing a **"Scroll to Top"** button would:
- Improve the website's accessibility and usability.
- Provide a smoother navigation experience, particularly on long articles or blog posts.
- Align the user interface with modern design practices.

I recommend adding a floating "Scroll to Top" button that becomes visible as users scroll down the page.

Please @ombhojane assign me this task with labels "GSSOC-Ext", "Hacktoberfest-accepted" and "level1".

**Comment by ombhojane** [comment]
Hey @archanasingh11 please look carefully, explainableai is a python package, we haven't provided any web interface yet!
