### ISSUE TITLE
in top hover adding home button

### ISSUE THREAD

**Issue by Aditijainnn** [ombhojane/explainableai#57]
![image](https://github.com/user-attachments/assets/eff87981-974b-4f9a-b67a-462e9b84f8f3)

in the top dashboard there is no buttom of home as we go in login page there is no option going back to home so adding that would make website more good
please assign this to me under gssoc ext and hacktoberfest

**Comment by ombhojane** [comment]
that's pypi package user interface, it's another website where we can list python packages.
