### ISSUE TITLE
[FEATURE] : add clear and consise comments to explaianble(0_1_6).ipynb  for better understanding of the code for visitor and reader

### ISSUE THREAD

**Issue by shravya312** [ombhojane/explainableai#58]
## Description
To get clear idea of the following:
The purpose of functions, classes, and modules.
The flow of data and control through the code.
Key algorithms, methodologies, and their parameters used in the machine learning processes.

## Problem it Solves
I want to make project beginner and readers friendly by adding clear and concise comments for improving the understanding of the project.

## Proposed Solution
Adding detailed, clear, concise comments to explaianble(0_1_6).ipynb

**Comment by ombhojane** [comment]
@shravya312 go ahead
