### ISSUE TITLE
[FEATURE] Add batch processing support for large dataset analysis

### ISSUE THREAD

**Issue by ombhojane** [ombhojane/explainableai#66]
Currently, when analyzing large datasets with the XAIWrapper, users may encounter MemoryError due to the entire dataset being processed at once. 
Implement batch processing in the analyze() method of XAIWrapper to handle large datasets efficiently.

Example Usage:
```python
xai.analyze(batch_size=1000)
```

### Suggested Approach

1. Modify the analyze() method to accept a batch_size parameter
2. If batch_size is provided:

   - Split the dataset into batches
   - Process each batch separately
   - Aggregate results from all batches

3. Implement memory-efficient aggregation of results
4. Update progress logging to show batch progress

### Code Considerations

- Handle edge cases (last batch might be smaller)
- Ensure consistent results between batched and non-batched processing
- Consider parallel processing for faster execution
- Maintain backward compatibility

```python
def processin_batches(self, X, batch_size):
    results = []
    for i in range(0, len(X), batch_size):
        batch = X[i:i + batch_size]
        batch_result = self._analyze_batch(batch)
        results.append(batch_result)
    return self._aggregate_results(results)
```

**Comment by Prakhar29Sharma** [comment]
I would like to work on this, can I get this assigned?. Any guidance is appreciated!

**Comment by softcreations01** [comment]
I would like to work on this project and modify the existing code to handle large datasets efficiently by processing them in smaller chunks.

**Comment by ombhojane** [comment]
@Prakhar29Sharma has been assigned

**Comment by KunjShah95** [comment]
IF THIS ISSUE IS OPEN CAN U KIDNLY ASSIGN IT TO ME
