### ISSUE TITLE
Improve Console Output Readability with Enhanced Print Formatting

### ISSUE THREAD

**Issue by ombhojane** [ombhojane/explainableai#7]
Make console output more readable by improving print formatting.

- Add color to important messages using the `colorama` package

**Example:**
```python
from colorama import Fore, Style

# Before
print("Analyzing model...")

# After
print(f"{Fore.BLUE}Analyzing model...{Style.RESET_ALL}")
print(f"Accuracy: {accuracy:.3f}")

**Comment by AnujSaha0111** [comment]
can you assign it to me

**Comment by ombhojane** [comment]
Hey @NikhilJ2005 to avoid conflicts, currently it's assigned to one contributor. Please look for other open issues.

**Comment by AnujSaha0111** [comment]
I have submitted, but it is not showing submitted on hacktoberfest or gssoc webssite

**Comment by ombhojane** [comment]
It has a latency of 6 hrs, would take some time to reflect on dashboard

**Comment by AnujSaha0111** [comment]
ok Sir, thanks
