### ISSUE TITLE
[FEATURE] Adding exception handling in feature_interaction.py for missing data, mismatched shapes

### ISSUE THREAD

**Issue by shravya312** [ombhojane/explainableai#71]
## Description
Logging issues: If something goes wrong (e.g., missing data, mismatched shapes), logging can give you a clear understanding of what failed.
It improves debugging

**Comment by shravya312** [comment]
Can u assign this issue to me @ombhojane

**Comment by shravya312** [comment]
Can u assign this to me @ombhojane

**Comment by Sai-ganesh-0004** [comment]
hello I interested in this can you assign it to me

**Comment by ombhojane** [comment]
@shravya312 go ahead

**Comment by shravya312** [comment]
Can u add gssoc extended and level labels @ombhojane

**Comment by shravya312** [comment]
Completed with this issue, pr number #112 @ombhojane
