### ISSUE TITLE
Explainable AI Integration for Time Series Model Interpretability

### ISSUE THREAD

**Issue by sharayuanuse** [ombhojane/explainableai#82]
## Description

This feature aims to enhance time series analysis by integrating the Explainable AI (XAI) package into the workflow. Users will be able to visualize temporal data, understand the factors influencing model predictions, and generate comprehensive reports. The integration includes applying stationarity tests, estimating model parameters using ACF and PACF plots, and utilizing the Explainable AI package to interpret model outputs. All visualizations and explanations will be saved as images within the same Colab notebook and compiled into a PDF report.

## Problem it Solves

- Lack of Interpretability in Time Series Models: Traditional time series models like ARIMA or SARIMA often act as "black boxes," making it difficult for users to understand how input features affect predictions.
- Difficulty in Visualizing Temporal Feature Importance: Users struggle to identify which time-based features (e.g., trend, seasonality) are most influential in their models.
- Inefficient Reporting Process: Manually generating and compiling visualizations and explanations into reports is time-consuming and prone to errors.

## Proposed Solution

- Explainable AI (SHAP) Integration: Leverage the SHAP (SHapley Additive exPlanations) library to explain the feature importance of time series models. SHAP values help users understand the individual contribution of features, even for complex models like SARIMA, ARIMA, or any tree-based regression model used in time series forecasting.
- Temporal Feature Importance: Implement time-specific explanations where SHAP values can highlight how certain time periods or lags contribute to the predictions.
- Model Explainability Visualization: Generate SHAP summary plots and force plots, illustrating how different features impact model outcomes across time. This will be crucial for both forecasting and general time series modeling tasks.
- Report Generation: All visualizations, including SHAP plots and time series plots, will be automatically compiled into a PDF report. This allows users to have a structured output summarizing both the temporal patterns and the explainability analysis of the model.

## Alternatives Considered
- LIME: Another explainability method, LIME (Local Interpretable Model-agnostic Explanations), was considered, but SHAP provides more reliable global explanations, especially for tree-based models and regression models, making it a better fit for time series.
- Manual Feature Analysis: Instead of using SHAP, manual feature importance analysis using correlation metrics or simple feature elimination could be implemented, but these would be less sophisticated and not as visually informative as SHAP.

## Additional Context
![sarima_forecast](https://github.com/user-attachments/assets/f9ba63b5-65b5-4cf9-a904-1dfc0d289c94)
![seasonal_decomposition](https://github.com/user-attachments/assets/f91974d3-e1e7-4f9d-b01b-58820a01498a)
![shap_summary](https://github.com/user-attachments/assets/35909eb3-ba38-4221-88c0-349e1ca6e05b)
![acf_pacf_plot](https://github.com/user-attachments/assets/6726dace-1771-4ca9-a89d-d47aaed65ecb)

**Comment by ombhojane** [comment]
Yes @sharayuanuse go ahead!
feel free to reach out,
update the core explaianbleai codes such that user can perform time series models efficiently with explainableai, as it's currently compatible with scikitlearn models

**Comment by sharayuanuse** [comment]
@ombhojane can you review this PR.
