### ISSUE TITLE
[BUG] Update the README file 

### ISSUE THREAD

**Issue by alo7lika** [ombhojane/explainableai#84]
## Description

The file can be updated by adding some pictures and enhancing it look to make it attractive and drive people to look for the projects

## Steps to Reproduce

2. Click on '...'
3. Scroll down to '...'

## Expected Behavior

Updating the Readme look for a better understanding

## Screenshots (if applicable)
N/A

**Comment by alo7lika** [comment]
ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 . Would like to enhance the Readme.md @ombhojane

**Comment by ShadowyBliss** [comment]
I would like to update the README file.

**Comment by alo7lika** [comment]
> ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 . Would like to enhance the Readme.md @ombhojane

@ombhojane .Assign me this work

**Comment by ombhojane** [comment]
hey @alo7lika can you elaborate about what type of images would be there for clarity
any example readme references would be a plus!

**Comment by alo7lika** [comment]
> Hey @alo7lika, can you elaborate on what type of images would be there for clarity? Any example readme references would be a plus!

https://github.com/abhisheknaiidu/awesome-github-profile-readme.git
Attached, a link of a README.md which you could take as an example of the enhancement of the frontend look that could allow the audience actually to visit and learn and allow more  interaction

**Comment by ombhojane** [comment]
hey @alo7lika go ahead!

**Comment by alo7lika** [comment]
@ombhojane I have created a pull request you can view it.
